### PR TITLE
Feat/address view

### PR DESCRIPTION
**Pull request by JDonadio**
Fixes https://github.com/bitpay/copay/issues/5020

* Addresses limit = 5 (for both lists)
* View all addresses **button** displayed if *any list length > 5*
* View all addresses > list of **all addresses**
* Remove duplicated information in *preferences > wallet > adnvanced > wallet information*
* Add popover menu with options (below)
* Migrate **scan/send** addresses functionality to addresses views

### CODE REVIEW

**Comment by bitjson** [comment]
@JDonadio for the icon, you can use `www/img/tab-icons/ico-receive-selected.svg` in the same way `addressbook.html` does:

```
      <i class="icon zero-state-icon">
        <img src="img/tab-icons/ico-receive-selected.svg"/>
      </i>
```

**Comment by gabrielbazan7** [comment]
On "Wallet Information" view, "Latest Wallet Addresses" option should be remove ?

screenshot_20161117-155522

What about "Scan address for fund" and "Send addresses by email" buttons

screenshot_20161117-155515

**Comment by JDonadio** [comment]
Fixed icon @bitjson.

Good point @gabrielbazan7, @bitjson what do you think about that? seems like we have duplicated info in both views

**Comment by cmgustavo** [comment]
ACK. Good job!

**Pull request merged**
