### PR TITLE
fixes routes issue on ionic 1

### LINKED ISSUE #5175: Back arrow in the top-left corner of the wallet screen can disappear
I have had this happen a couple of times, but I'm not sure how I did this or how to reproduce. The back arrow on the wallet home screen disappeared for a while, and then randomly reappeared again.

It doesn't disappear while I am sitting there on the screen, only which I switch to it from another screen.

### PR DESCRIPTION
**Pull request by gabrielbazan7**
fixes #5175 #4867 #5311

To reproduce the error: 

1. Go to "Home Tab".
2. Go to "Wallet Details" clicking on a wallet.
3. Click on backbutton.
4. Go to "Send Tab".
5. Go to "Amount" clicking on a wallet.
6. Click on backbutton
7. Repeat 1, 2, 3, 4, 5

### CODE REVIEW

**Comment by cmgustavo** [comment]
NACK. We can't add the `ionic-history` condition for each page that we think could fail.

**Comment by gabrielbazan7** [comment]
The ones that fails are the Tabs sub pages.

**Comment by gabrielbazan7** [comment]
this issue is solved on this PR https://github.com/driftyco/ionic-v1/pull/210

**Comment by JDonadio** [comment]
No longer needed.

**Pull request closed without merging**
