### PR TITLE
feedback feature refactor

### PR DESCRIPTION
**Pull request by gabrielbazan7**

### CODE REVIEW

**Comment by bitjson** [comment]
@gabrielbazan7 please let me know when this is ready for me to review. (And how to best test every case.)

**Comment by JDonadio** [comment]
You have to play with this object in localStorage:

copay_-_copay_bitcoin_wallet

* time > ts to calculate 24 +
* version > latest Copay version stored

**Comment by bitjson** [comment]
Reviewing today

**Comment by JDonadio** [comment]
LGTM

**Pull request merged**
