### PR TITLE
Bug/angular twice

### PR DESCRIPTION
**Pull request by matiu**
- Fix Angular warning  at startup.
 - Fix test's fixtures with singleAddress param
 - Enhance error message with importing a non existent wallet

### CODE REVIEW

**Comment by matiu** [comment]
Updated, ready for review.

**Comment by cmgustavo** [comment]
Code ACK. Travis failed when creating wallet from mnemonic.
Also, please remove the `console.log`.

**Comment by matiu** [comment]
updated. Thanks for the review.

**Comment by cmgustavo** [comment]
ACK!

**Pull request merged**
