### PR TITLE
fix connection error messages to be grammatically correct

### PR DESCRIPTION
**Pull request by jlopp**
This was annoying me when I was using copay.

On a related note, I received these messages a lot and my connection was fine - I suspect that the problem may have actually been on the Bitcore Wallet Service's end.

### CODE REVIEW

**Comment by cmgustavo** [comment]
Hello @jlopp, thanks a lot for your contribution! 

Respect your code, you shouldn't modify the .PO files. The only files you have to commit are `template.pot` and `walletHome.js`. After that, we have to upload the pot file to Crowdin and each translator will have to update their language.

**Comment by jlopp** [comment]
Alright, should be only those relevant files now. FYI, it looks like the connection errors I was receiving were a result of using Copay through Tor - you might want to add this as a goal to provide better Tor support.

**Comment by dabura667** [comment]
LGTM

**Comment by matiu** [comment]
thanks for the contribution!

**Pull request merged**
