### PR TITLE
change splash

### LINKED ISSUE #2979: Copay splash screen looks blurred in Android
This is a small UI issue. [copayscreen.png](https://github.com/bitpay/copay/blob/master/cordova/android/res/drawable-port-xhdpi/copayscreen.png) needs to have a Full HD resolution in order to look sharp.

### PR DESCRIPTION
**Pull request by bechi**
Fixes #2979

### CODE REVIEW

**Comment by cmgustavo** [comment]
Android has 4 screen size (portrait): `small`, `normal`, `large` and `extra-large`. 
Then you have density for each screen: `low`, `medium`, `hight` and `extra-hight`.

For example, normal screen size, you could have these values for each density: 
* LDPI (120): 200x320px
* MDPI (160): 320x480px
* HDPI (240): 480x800px
* XHDPI (320): 720px1280px

So, I think the idea is maintain the same resolution of images and improve the quality (dpi). Take a look this: http://developer.android.com/guide/practices/screens_support.html and http://stackoverflow.com/questions/10574363/android-splash-screen-image-sizes-to-fit-all-devices

**Comment by sironitomas** [comment]
Why hasn't this been pulled?

**Comment by bechi** [comment]
Try with this commit, maybe the problem has been resolved

**Comment by cmgustavo** [comment]
The images have now more quality, but the logo `Copay` is still blurred. I don't know what was the original issue, the bad quality of Copay logo or the weird bands.

**Comment by sironitomas** [comment]
I know what's the issue. Many phones now come with a Full HD resolution. That is 1080x1920px. The biggest splash is 720x1280px. When you stretch that image to Full HD, it will look blurred. The solution is to render a bigger, xxhdpi image.

**Comment by cmgustavo** [comment]
I see. So we have to add the follow new images/folders: 

* XXHDPI: Portrait: 960 X 1600px.
* XXXHDPI: Portrait: 1280 X 1920px.

BTW, I figured it out that the xhdpi has bad resolution: (it has 640px X 960px instead 720px X 1280px). Also the ldpi should have 200 X 320px.

**Comment by sironitomas** [comment]
That's correct. I'd do it but I have no vector image logo of Copay.

**Comment by bechi** [comment]
I already add 2 folder with these sizes and also I remove the gradient. Maybe all problem resolved in this commit :) . Thanks for your feedback.

**Comment by sironitomas** [comment]
Looks perfect now. This should be merged into master ;)

Thanks!

**Comment by bechi** [comment]
Thanks you @sironitomas

**Pull request merged**
