### PR TITLE
Fixes for recent and txps transactions cards

### PR DESCRIPTION
**Pull request by gabrielbazan7**
Before:

copay_-_copay_bitcoin_wallet

Now: 
copay_-_copay_bitcoin_wallet

### CODE REVIEW

**Comment by rastajpa** [comment]
ACK! (tested on desktop and android)

**Comment by bitjson** [comment]
@gabrielbazan7 In the screenshot above, the `0.001 BTC` now wraps to show `0.001
BTC` . Can we fix that?

Also, it seems like the font size just needs to come down on the title. (Isn't that font size just much larger than in other places?) I think it's still cleaner to have the time string right-aligned.

**Comment by gabrielbazan7** [comment]
What to do think about this @bitjson ?

copay_-_copay_bitcoin_wallet

**Comment by bitjson** [comment]
Awesome! Much better. 

Are the headings all the same size? (Might be an optical illusion, but they seem slightly larger.)

It might be a little cleaner if we make the Proposals and Recent Transactions icons smaller? (So they appear to be the same height as the wallet's name – probably the same size as the bitcoin icon.) 

And for the Recent Transactions card, should we try to render the wallet icon inside the box (instead of just the solid color)? As it is, it almost feels like the image didn't download properly and isn't being displayed. So the smaller icons would look like the wallet icons, just scaled down.

**Pull request merged**
