### PR TITLE
Improve scanner handling on all platforms

### PR DESCRIPTION
**Pull request by bitjson**
Fixes: #4935, #4967, #5172, #4946, and #4831

### CODE REVIEW

**Comment by matiu** [comment]
Please note that this seems to also happen on mobile.

eg.  is you turn on the flash on mobile and navigate away from the scanner, the flash will stay on indefinitely.

**Comment by bitjson** [comment]
@matiu this PR is only for the "privacy light" (little green light by the camera), and there are currently no mobile devices with privacy lights. So I think this only concerns the desktop build.

On what you mentioned – would you expect the flash to work differently? If you tap the scan tab again, the flash button is still highlighted, right?

I guess we could disable the light if the user navigated away, but I think it's probably a better experience for the light to only activate/deactivate when the user taps the button. If the user is in a dark room and activated the light to scan a printed QR code, I would think the light should stay on until the user deactivates it.

**Comment by bitjson** [comment]
I'm still reviewing on mobile devices. These are small changes, but the logic is pretty complicated, so I'd like to be very sure it's completely correct now.

**Comment by bitjson** [comment]
This is ready for review. It would be good to test a bit more on Android, particularly.

**Comment by cmgustavo** [comment]
It works for me: (iOS and macOS).

But in the mobile I can see that after turning on the light, this still active after changing tab.

**Comment by bitjson** [comment]
@cmgustavo – see [above](https://github.com/bitpay/copay/pull/5440#issuecomment-273573385) - I don't think that's a bug. 

> I guess we could disable the light if the user navigated away, but I think it's probably a better experience for the light to only activate/deactivate when the user taps the button. If the user is in a dark room and activated the light to scan a printed QR code, I would think the light should stay on until the user deactivates it.

Would you expect it to work differently? I tried a bit both ways, and it seems more intuitive like this? (I don't have a strong opinion on it though, I could switch it)

**Pull request merged**
