### PR TITLE
Feedback feature

### PR DESCRIPTION
**Pull request by gabrielbazan7**
Needs design.

### CODE REVIEW

**Comment by JDonadio** [comment]
Code was cleaned up. @bitjson can you take a look ? I think this is ready! 🎉

**Comment by bitjson** [comment]
Could we get some info on how best to manually test this? How can I modify my local storage to retry, etc? Looking great so far!

On first review, the 5/5 feedback flow dropped me right into the text entry screen, when it should have taken me to the Thank you / rate view. I still need to step through the other flows.

**Comment by JDonadio** [comment]
@bitjson try modifying this:

copay_-_copay_bitcoin_wallet

**Comment by gabrielbazan7** [comment]
@bitjson sorry, just fixed.

**Pull request merged**
