### PR TITLE
Fix label and icon size

### PR DESCRIPTION
**Pull request by JDonadio**
Fixes https://github.com/bitpay/copay/issues/5901
Also fixes the icon size

copay_-_copay_bitcoin_wallet

### CODE REVIEW

**Comment by gabrielbazan7** [comment]
The time div needs `white-space: nowrap`property 

copay_-_copay_bitcoin_wallet

**Comment by gabrielbazan7** [comment]
copay_-_copay_bitcoin_wallet

**Comment by gabrielbazan7** [comment]
I send a PR with that changes https://github.com/JDonadio/copay/pull/61

**Comment by JDonadio** [comment]
Great job, thank you!

**Pull request merged**
