### PR TITLE
update-pt-br-translation

### PR DESCRIPTION
**Pull request by pmichelazzo**
Updating the PT-BR translation

### CODE REVIEW

**Comment by cmgustavo** [comment]
I have an update of this file on my PR (https://github.com/bitpay/copay/pull/2846), and I also renamed the PO file to do it fully compatible with our schema. For now, we are using generic translation (I mean, not country specific). Could you update your po file (pt.po) since my PR (#2846) be merged?

Thanks a lot for your contribution!

**Comment by pmichelazzo** [comment]
Hi @cmgustavo,

Yes, sure. go ahead with your merge. After that, I will check again.

Cheers

**Comment by matiu** [comment]
sorry, needs rebase.

**Comment by cmgustavo** [comment]
Hi @pmichelazzo, I think this PR is not necessary any more, because on it (#2846) we are already including the option to select PT language. I will close it for that reason. Please, feel free to open another PR with your corrections.

Thanks!

**Pull request closed without merging**
