### PR TITLE
hide advanced options from send form

### LINKED ISSUE #3222: Remove advanced options from send tab

### PR DESCRIPTION
**Pull request by javierbitpay**
fixes #3222

### CODE REVIEW

**Comment by dabura667** [comment]
So this will mean all transactions follow the wallet preferences?

**Comment by matiu** [comment]
NACK.

On Mon, Sep 28, 2015 at 11:05 AM, dabura667 <notifications@github.com>
wrote:

> So this will mean all transactions follow the wallet preferences?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/pull/3245#issuecomment-143752294>.
>



-- 
BitPay.com

**Comment by dabura667** [comment]
NACK as well. Until I hear a good reason.

**Comment by isocolsky** [comment]
I am ok with this change. I don't think the advanced options are useful. It just adds complexity to the send tab with no real gain: it is not needed by casual users and it does not add enough control for power users. Have you ever needed to change these settings for a single transaction?

**Pull request closed without merging**
