### PR TITLE
Wallet service errors

### PR DESCRIPTION
**Pull request by JDonadio**

### CODE REVIEW

**Comment by ajp8164** [comment]
We may not need the new "if" statements in walletService.js because the errors are not changed from BWC (I think they will end up being noops).  bwcErrors should be able to work fine with the just the `return cb(err)` statement.

**Comment by JDonadio** [comment]
You're right @ajp8164, thanks!
Updated.

**Comment by JDonadio** [comment]
We need to do a complete review of errors at BWC. For now, errors like `WALLET_NOT_REGISTERED` are not be handling correctly.

**Comment by gabrielbazan7** [comment]
ACK

**Comment by gabrielbazan7** [comment]
ACK

**Pull request merged**
