### PR TITLE
fix sweep paper wallet backup message

### LINKED ISSUE #4842: "Backup Needed" view should allow user to do the backup
_From @bitjson on October 18, 2016 16:24_

"Preferences" should be changed to "Backup Now", and take the user to the "are you being watched?" screen.

slack_for_ios_upload_720-3

_Copied from original issue: bitpay/bitpay-wallet#543_

### PR DESCRIPTION
**Pull request by gabrielbazan7**
fixes #4842

### CODE REVIEW

**Comment by cmgustavo** [comment]
Needs rebase

**Comment by gabrielbazan7** [comment]
Updated

**Comment by matiu** [comment]
code ACK

**Comment by cmgustavo** [comment]
ACK

**Pull request merged**
