### PR TITLE
[Feat]: New Onboarding

### PR DESCRIPTION
**Pull request by rastajpa**

### CODE REVIEW

**Comment by cmgustavo** [comment]
A few comments:

- [ ] Mobile: Select import -> Enter PIN -> back -> white screen
- [ ] Mobile: Select import -> on PIN view -> Cancel -> white screen
- [ ] Mobile: app get stuck on PIN view after resume before finish onboarding
- [ ] Mobile: numeric keyboard doesn’t respond when app resume
- [ ] Mobile: key number show not show chars
- [ ] Desktop: Adds buttons
- [ ] Desktop: remove PIN
- [ ] Desktop: fonts too big on last step

**Screenshots (desktop)**
Screen Shot 2020-11-02 at 18 01 01
Screen Shot 2020-11-02 at 17 56 06

**Comment by cmgustavo** [comment]
We need to track users step through the new onboarding in order to learn if they end it or leave it. Is that possible? What do you think @vanhue ?

**Comment by cmgustavo** [comment]
Regarding CircleCI error, I think there's something wrong in test itself. 

* Local test of this branch takes: HeadlessChrome 86.0.4240 (Mac OS X 10.15.7): Executed 574 of 575 (skipped 1) SUCCESS (1 min 56.928 secs / 0 secs)

Local test of `master` branch takes: HeadlessChrome 86.0.4240 (Mac OS X 10.15.7): Executed 575 of 576 (skipped 1) SUCCESS (53.887 secs / 0 secs)

There's more than 1 minute and only 1 test added.

**Comment by rastajpa** [comment]
@cmgustavo Thanks for the feedback!


A few comments:
 
 * [x]  Mobile: Select import -> Enter PIN -> back -> white screen
 * [x]  Mobile: Select import -> on PIN view -> Cancel -> white screen
 * [x]  Mobile: app get stuck on PIN view after resume before finish onboarding
 * [x]  Desktop: Adds buttons
 * [x]  Desktop: remove PIN
 * [x]  Desktop: fonts too big on last step
^The font size follows the design. please review the prototype in invision. But it's a good point, so I added the ability to scroll if the user requires it.

 * [ ]  Mobile: numeric keyboard doesn’t respond when app resume 
^ Please test it in a real device. I couldn't reproduce it after several attempts
 * [ ]  Mobile: number "1" looks unaligned to the other numbers
^ Nothing was changed in this PR regarding the keyboard. So we should open a new ticket to deal with this issue separately and study which devices are affected.

**Comment by rastajpa** [comment]
> Regarding CircleCI error, I think there's something wrong in test itself.
> 
> * Local test of this branch takes: HeadlessChrome 86.0.4240 (Mac OS X 10.15.7): Executed 574 of 575 (skipped 1) SUCCESS (1 min 56.928 secs / 0 secs)
> 
> Local test of `master` branch takes: HeadlessChrome 86.0.4240 (Mac OS X 10.15.7): Executed 575 of 576 (skipped 1) SUCCESS (53.887 secs / 0 secs)
> 
> There's more than 1 minute and only 1 test added.

Checking it

**Comment by gabrielbazan7** [comment]
ACK! testnet on IOS

**Review by cmgustavo — APPROVED** [review]
Great work! 🚀

**Pull request merged**
