### PR TITLE
Bug/nw quota

### PR DESCRIPTION
**Pull request by matiu**

### CODE REVIEW

**Comment by cmgustavo** [comment]
ACK! Tested on Windows, Linux and OSX with existent wallets

**Comment by braydonf** [comment]
Run this on Ubuntu and it looks like it works. I did notice that once migrated, older clients will think that there isn't any data, and will start with the normal welcome screen.

**Comment by matiu** [comment]
updated. Test passing!

**Comment by matiu** [comment]
Thanks @cmgustavo and @braydonf for testing!

**Pull request merged**
