### PR TITLE
Add localization for Google Play store

### PR DESCRIPTION
**Pull request by dabura667**
Japanese people have been saying "Apps with no Japanese description are shady"

So here's your Japanese description.

You can copy paste from the JA file into the account for the ja language people.

I also added the en file just as point of reference (on what to copy etc) and so other languages have a format to follow.

I think we should add the iOS appstore description etc. and if you can write the "This versions new things" there I can probably translate within 24 hours most the time.

Too many languages might make it a pain for the person managing the stores, so maybe if someone could look into a way of automating the process?

### CODE REVIEW

**Comment by dabura667** [comment]
@Kirvx Maybe you can translate French too?

**Comment by dabura667** [comment]
btw unrelated, but I gave a shout out to you guys in a presentation I gave a short while back to the dev community. We then had a workshop where everyone installed copay and we sent money around. It was very fun and they all learned a lot about multisig and bitcoin.

https://docs.google.com/presentation/d/1C8maTX4v0-ksFJoqfwyyv-DQ4WXB1pYFPcUXEfdC928/edit?usp=sharing

**Comment by matiu** [comment]
Nice!! FTW!!! :)

**Comment by matiu** [comment]
Thanks for sharing the presentation! We are happy you find Copay useful and exited with all you contributions to the proyect!

Do you have a twitter handle?

**Comment by matiu** [comment]
PS: We will update the stores in the next few days.

**Comment by dabura667** [comment]
Cool. I hear Apple can change description even after submitting a build for release. (Have you already submitted to Apple?)

I don't use twitter very much. but I have one. Do you have a PGP public key for me to encrypt it with?

**Pull request merged**
