### PR TITLE
Create Tesssssd

### PR DESCRIPTION
**Pull request by 444445555555555**

### CODE REVIEW

**Comment by dwcoen123** [comment]
What is this and what is it for? I have

Daniel wayne coen Not been able to gain access to my bitpay a wallet and I
am trying to reset the 4 digit pin on the front of my phone but I can't
remember the old pin to open the wallet and I and I have my 12 words but
I'm not sure if they are corresponding to this wallet I hit the QR Code
that was on when I searched my address my legacy address and that was on
bitcoin.com and when I tap the QR Code at the top of the Explorer screen it
goes directly to my bitpay wallet and I was told by the people on the phone
customer service that meant that that was in my bed pay wallet and I am
confused because if it is then that's 5 million dollars of my money and I
cannot access that money and I would like to to know why I'm receiving this
information here is it a fix to something has somebody been withdrawing
from my account of a copay wallet that I have and F and if so it was not me
that we did any withdrawals so please text me back and let me know

**Comment by sajadvilsin-cmyk** [comment]
@sajadvilsin

**Comment by sajadvilsin-cmyk** [comment]
@sajadvilsin

**Comment by sajadvilsin-cmyk** [comment]
@sajadvilsin-cmyk >

**Comment by sajadvilsin-cmyk** [comment]
@sajadvilsin-cmyk >

**Pull request closed without merging**
