### PR TITLE
Added untranslated strings

### PR DESCRIPTION
**Pull request by dabura667**
btw is using gettext() with `$scope.ok` and `$scope.cancel` etc. ok to do?

### CODE REVIEW

**Comment by cmgustavo** [comment]
Need rebase.

I think `navigator.notification.*` doesn't work with gettext.

**Comment by dabura667** [comment]
The problem I am trying to fix with this is that iOS app and Android app have the "Confirm" "Are you sure you want to delete wallet?" in English.

Kind of important that the user understands what this means. :-)

I rebased and restructured to make the localization its own string variable, then just use that.

**Comment by cmgustavo** [comment]
I know what you mean, but it 's still not working with the cordova plugin `navigator.notification`. I tested it on iPhone:

Note that I have it in spanish, but the popup is in english.

screenshot_7_27_15__09_53

I think it happens with all others notification that uses the plugin.

**Comment by dabura667** [comment]
Hmm... well, I can't figure it out... so I will close this PR and make it an issue instead.

**Comment by cmgustavo** [comment]
Hi @dabura667 , 

Maybe you want to open it again, I have the solution:

To translate in-file you should use:
```
gettextCatalog.getString('string');
```
This replace the text before to do `navigation.notification` or call another cordova plugin. It works to me. Please, If you can, just replace `gettext` by `gettextCatalog.getString` and updated the PR. I could update all the other messages used by cordova plugins.

**Comment by dabura667** [comment]
ok, I will do it in a few hours or less.

**Pull request closed without merging**
