### PR TITLE
fix(topup): show Coinbase accounts after enter amount in cryptocurrency

### PR DESCRIPTION
**Pull request by cmgustavo**

### CODE REVIEW

**Comment by rastajpa** [comment]
BitPay
I can't see the alt currency amount in the wallet selector

**Comment by cmgustavo** [comment]
> BitPay
> I can't see the alt currency amount in the wallet selector

Good catch. I'll take a look, thanks!

**Comment by cmgustavo** [comment]
Weird, after testing a few times, I always see the fiat value.
Maybe it's a connection issue. I'll add a conditional to avoid that

Thanks!

**Review by rastajpa — APPROVED** [review]
ACK!

**Review by gabrielbazan7 — APPROVED** [review]

**Pull request merged**
