### PR TITLE
fix : Scanner and keyboard at same time

### LINKED ISSUE #4856: Scanner and keyboard at same time
_From @ajp8164 on October 18, 2016 23:53_

When I click camera button from add new address I get both the camera and the keyboard.

img_4490

_Copied from original issue: bitpay/bitpay-wallet#573_

### PR DESCRIPTION
**Pull request by gabrielbazan7**
fixes #4856
Also fix extra-padding on Android keyboard

### CODE REVIEW

**Comment by cmgustavo** [comment]
The `addressbook.add.html` still uses `qr-scan-icon`

**Comment by JDonadio** [comment]
copay_-_copay_bitcoin_wallet

**Comment by gabrielbazan7** [comment]
Updated

**Comment by matiu** [comment]
need rebase.

**Comment by gabrielbazan7** [comment]
Updated

**Comment by JDonadio** [comment]
ACK

**Pull request merged**
