### PR TITLE
[FEAT] new release msg

### PR DESCRIPTION
**Pull request by gabrielbazan7**
BitPay

### CODE REVIEW

**Comment by vanhue** [comment]
@gabrielbazan7 will there be a way to dismiss that message?

**Comment by gabrielbazan7** [comment]
> @gabrielbazan7 will there be a way to dismiss that message?

No, the user will need to update the app to make the message disappear. But I'm not sure, what do you think ?

**Comment by vanhue** [comment]
If it's only for desktop then it should be fine. 👍

**Comment by cmgustavo** [comment]
It should be possible to close.... so waiting for it

**Pull request merged**
