### PR TITLE
Improve Integrations UX (Buy & Sell, Amazon)

### PR DESCRIPTION
**Pull request by bitjson**
This PR provides a clearer Buy & Sell Bitcoin onboarding experience, and sets proper expectations earlier in the process. Also improves the onboarding for the Amazon.com gift cards integration.

### CODE REVIEW

**Comment by bitjson** [comment]
@cmgustavo: weird – thanks for noticing. Looking at that now.

**Comment by bitjson** [comment]
To do:
- reproduce and fix the issue with the bitcoin icon
- update the amazon integration landing view to match the other integrations

**Comment by bitjson** [comment]
screen shot 2017-02-03 at 11 56 15 am

So this is very strange ^ – `icon-bitcoin.svg` is just not loading in the iOS webview. Working fine in safari and chrome on desktop.

**Comment by bitjson** [comment]
@cmgustavo – fixed those issues, and also improved the design of the Amazon integration. Mind reviewing again?

**Comment by cmgustavo** [comment]
ACK. Nice job!

**Pull request merged**
