### PR TITLE
Updates po files

### PR DESCRIPTION
**Pull request by cmgustavo**

### CODE REVIEW

**Comment by dabura667** [comment]
Hold on, I'll get the Japanese done in a few minutes.

Did you submit to apple already?

**Comment by cmgustavo** [comment]
Don't worry. We can wait for the jp.po :)

It 's not ready to submit yet.

**Comment by dabura667** [comment]
OK done with Japanese on crowdin.

I am not on my home computer so I can not make a PR, so if you could please merge the new Japanese po file and update info file I would appreciate it.

Can't wait for this update!

**Comment by cmgustavo** [comment]
Sure! Thanks!

**Pull request merged**
