### PR TITLE
 Update resource generation flow (iPhone X, latest iOS splash images)

### PR DESCRIPTION
**Pull request by bitjson**
Replaces #8397 (cleaner PR)

### CODE REVIEW

**Comment by cmgustavo** [comment]
Needs rebase

**Comment by bitjson** [comment]
Waiting on https://github.com/bitpay/copay/pull/8457 (fixes tests)

**Comment by cmgustavo** [comment]
Done. #8457

**Comment by msalcala11** [comment]
ACK! 🚀

**Pull request merged**
