### PR TITLE
Ledger + Mnemonics

### PR DESCRIPTION
**Pull request by matiu**
This joins
https://github.com/bitpay/copay/pull/3126
and 
https://github.com/bitpay/copay/pull/3011

Both PR need to be merged at the same time.

Implements ledger hardware wallet support in Copay ChromeApp, and support mnemonics for wallet seeds.  Now is possible to recover a wallets from a mnemonic only.

### CODE REVIEW

**Comment by matiu** [comment]
Updated with 'import' support.

Ready for review and merge.

**Comment by cmgustavo** [comment]
Awesome work @EricLarch and @matiu !!

I did some manual test and everything seems to work as expected. 

* Create wallet using ledger hardware. Delete wallet and recreate it again.
* Import a wallet using ledger hardware from my own (and empty) BWS.
* Sign transaction with ledger hardware.
* Import a wallet from 12 words backup

Please, let me know if there is another case to test.

**Comment by EricLarch** [comment]
Great! Can you confirm you are seeing only one popup on the Ledger Chrome app when creating a wallet? 

Regarding test case, you should also test joining a wallet as a co-signer with the Ledger.

**Comment by matiu** [comment]
Yes. Only one popup is shown when creating a wallet. (Xpub Derivation of m/0'/45'). The magic number at the path is working as expected.

**Comment by cmgustavo** [comment]
Yes, I am seeing only one popup to create a wallet. 

* I joined from Copay with Ledger and normal wallet and vice versa. OK
* Create and sign a transaction from Copay with Ledger and broadcast with the other copayer.
* Recovery a wallet into Copay only with 24-words Ledger.

Everything LGTM.

**Comment by matiu** [comment]
ToDo: add a signService for `fc.signTxProposal` so this will work with https://github.com/bitpay/copay/pull/3145

**Comment by cmgustavo** [comment]
ACK. Manual test: everything seems to be well. Create, join, send and sign with Copay-Legder. Recovery ledger wallet from 12 words. Recovery from ledger hardware.

Great work guys!

**Comment by EricLarch** [comment]
To be sure, you mean recovery from 24 words?

**Comment by cmgustavo** [comment]
Yes! 24 words.

**Comment by EricLarch** [comment]
Perfect. Delighted to see Ledger support scheduled for the next release!

**Pull request merged**
