### PR TITLE
Fix disclaimer

### PR DESCRIPTION
**Pull request by dabura667**
This should make it so that the TM will save, and we won't have to try to dig up old po files to copy.

### CODE REVIEW

**Comment by cmgustavo** [comment]
I think the best way to do that is to link to the original document: https://copay.io/disclaimer

Something like this: 
```
<div ng-show="index.defaultLanguageIsoCode != 'en'>
  <a ng-click="$root.openExternalLink('https://copay.io/disclaimer')">Disclaimer</a>
</div>
```

What do you think?

**Comment by dabura667** [comment]
Sounds good, will add.

**Comment by Kirvx** [comment]
It's like you want.

**Comment by dabura667** [comment]
```
<p ng-show="index.defaultLanguageIsoCode != 'en'">
  <a class="center" ng-click="$root.openExternalLink('https://copay.io/disclaimer')">Original Disclaimer</a>
</p>
```
Even with this, I have my device set to 'en' and the link still shows up... even if I use div instead of p it still shows when language is en

**Comment by dabura667** [comment]
`index.defaultLanguageIsoCode` is `null` at the disclaimer screen.

**Comment by cmgustavo** [comment]
Yes, it 's not so simple.

This is my solution (already tested locally):

src/js/controllers/disclaimer.js
```
 angular.module('copayApp.controllers').controller('disclaimerController',
-  function($scope, $timeout, storageService, applicationService, gettextCatalog, isCordova) {
+  function($scope, $timeout, storageService, applicationService, gettextCatalog, isCordova, uxLanguage) {
...
$scope.init = function() {
       storageService.getCopayDisclaimerFlag(function(err, val) {
+        $scope.lang = uxLanguage.currentLanguage;
         $scope.agreed = val;
         $timeout(function() {
           $scope.$digest();
...
```

public/views/disclaimer.html
```
<p class="text-center" ng-show="lang != 'en'">
  <a ng-click="$root.openExternalLink('https://copay.io/disclaimer')">Original Disclaimer</a>
</p>
```

**Comment by dabura667** [comment]
All done. Have tested locally.

**Comment by cmgustavo** [comment]
Great! LGTM

**Comment by dabura667** [comment]
Can someone merge so I can upload to Crowdin and go to sleep? ( :-) )

**Comment by dabura667** [comment]
Thanks!

**Comment by Kirvx** [comment]
Nice it perfectly works, finally :)

**Pull request merged**
