### PR TITLE
Feature - Price charts using Apex Charts

### PR DESCRIPTION
**Pull request by justinkook**
relies on

https://github.com/bitpay/copay/pull/10641

### CODE REVIEW

**Comment by cmgustavo** [comment]
Please, don't add `package-lock.json`. We'll do it on a new bump (next version).

**Comment by justinkook** [comment]
> There is an error regarding currencies supported by Simplex.
> This is the correct listing.
> `AUD CAD CHF CZK DKK EUR HUF ILS JPY KRW NOK NZD PLN RUB SEK TRY USD ZAR`
> You can bring it from simplexProvider

fixed!

**Comment by gabrielbazan7** [comment]
ACK!!

**Comment by Gamboster** [comment]
Tested on my android. It looks good and the error with the currencies of Simplex was fixed.

Just to know... Why do we change from library chart.js to apexchart?

**Comment by justinkook** [comment]
You need a plugin to perform the same touch actions/animations as apex charts.

https://chartjs-plugin-datalabels.netlify.com/guide/

Also animations were better for apexcharts

**Comment by cmgustavo** [comment]
I'd prefer to disable this feature (select range). Is that possible?

Screen Shot 2020-03-16 at 14 45 00

**Comment by rastajpa** [comment]
needs rebase

**Pull request closed without merging**
