### PR TITLE
Re-enable Coinbase integration

### LINKED ISSUE #4894: Re-Enable Coinbase integration

### PR DESCRIPTION
**Pull request by cmgustavo**
fixes #4894

### CODE REVIEW

**Comment by cmgustavo** [comment]
Ready for review

**Comment by cmgustavo** [comment]
Updated

**Comment by matiu** [comment]
Great job!

**Comment by acars999** [comment]
Hello, I have read through the message chain.  It sounds like this issue is closed, but I just got the same error "Two-step verification code required to complete this request. Re-play the request with CB-2FA-Token header."  I just installed yesterday, so I would assume I downloaded the latest version with the fix.

I clearly remember setting up 2FA in Copay, with that crazy phrase that we had to WRITE down, with no ability to copy and paste.  Any way to fix that BTW?  Having to type that into lastpass is silly.

By the way, the coin purchase that led to the error actually did go through in Coinbase, and the coins posted to my Coinbase account.  I really would like to get Copay working.  Thanks!

**Comment by cmgustavo** [comment]
Hi @acars999 , regarding 2FA, Copay doesn't have 2FA. Not sure what do you mean. That phrase is all you need to recover your wallet, it 's important to write down.

Regarding the Two-step verification error, could you provide us some more information like your device and if you received an email from Coinbase that you are trying to link the account with Copay? 

Thanks.

**Comment by acars999** [comment]
Hello, and thank you for responding.

I thought that phrase was the 2FA.  Sorry I misunderstood.  It would be
really nice to be able to copy and paste that phrase though. I don't write
stuff like that down. I use a Password Manager for important things like
that.  Because if I write it down, I won't be able to find that piece of
paper when I need it.  Just a suggestion for a future change if it seems
appropriate...

Back to the Copay/Coinbase linkage issue...

I am using the Copay Chrome app, on a Dell Windows PC, with Windows 10 Pro.


I did receive emails from Coinbase confirming the linkage between Coinbase
and the Copay app (I tried multiple times).  Also, it shows as linked to
Copay on the Coinbase website under settings.

Additional detail I figured out after my first message to the thread last
night...

I am new to Bitcoin, and early in the learning stage. So please forgive me
if my understanding of the process flow is off...  From my observation, the
Copay app is acting like the linkage to Coinbase works - at least for
purchases.  I initiated the purchase of Bitcoin through Coinbase from
within the Copay app - and the purchase went through.  I have the Bitcoin
in my Coinbase wallet.  Once I realized it was there, I even purchased
something with it, sending the Bitcoin from my Coinbase wallet.  So the
Bitcoin purchase from within Copay worked.

Where it seemed to break, or at least where I got the error, is where the
Bitcoin should have been transferred into my Copay wallet from Coinbase.
Ultimately, I want to have a personal, local wallet like Copay, and not
store Bitcoin in a website-based wallet - least of all with the exchange
where I bought the Bitcoin.  If I understand it correctly, the Bitcoin
should have been transferred to my Copay wallet, and removed from my
Coinbase wallet - but this step broke down somehow.

With the amounts I am playing with now, its not the end of the world that
this transaction didn't work as planned.  But I would like to get it to
work eventually, so that I can use Copay to store my Bitcoin off of remote
servers, before I start dealing with larger amounts of Bitcoin.

I appreciate any help you can provide, and your patience with a Bitcoin
newby.

**Pull request merged**
