### PR TITLE
fix paper wallet scanner

### LINKED ISSUE #4866: Scanner doesn't scan paper wallets
_From @bitjson on October 20, 2016 23:5_

I know this is a feature request, but with the scanner being so "intelligent" with other data types, it will probably feel like a bug...

Ok for after 1.0

_Copied from original issue: bitpay/bitpay-wallet#621_

### PR DESCRIPTION
**Pull request by gabrielbazan7**

### CODE REVIEW

**Comment by bitjson** [comment]
What about scanning from the Scan tab?

**Comment by bitjson** [comment]
Was this broken? Issue #4866 is about adding paper wallet scanning to the scan tab. (If this is different, we can get this merged in, and finish #4866 later.)

**Comment by bitjson** [comment]
LGTM

**Comment by msalcala11** [comment]
LGTMAW

**Pull request merged**
