### PR TITLE
Fix/lang bug android

### PR DESCRIPTION
**Pull request by gabrielbazan7**
Fix : #3701

### CODE REVIEW

**Comment by tanojaja** [comment]
LGTM

**Comment by gabrielbazan7** [comment]
Updated

**Comment by cmgustavo** [comment]
I think we shouldn't use `async` function to set the language, because it 's necessary at bootstrapping. Perhaps some Android devices have different versions of the browser and return a false positive (in this line: https://github.com/bitpay/copay/pull/3707/files#diff-85bd5aff1692eb058e100ad2aaf83cfaL45).

**Comment by matiu** [comment]
Is this still valid?

**Comment by gabrielbazan7** [comment]
Still valid, because copay doesn't recognize the language that is set by the user in some android phones. Now, with the latest update of Copay ( https://github.com/bitpay/copay/pull/3752 ), set english as default if this happen, so there will be not mixed languages on activity screen (this issue https://github.com/bitpay/copay/issues/3701 is solved). But, the problem still there.

**Comment by cmgustavo** [comment]
Ok. It works for me (Android and NW).
Please rebase is needed.

**Comment by gabrielbazan7** [comment]
Updated

**Comment by cmgustavo** [comment]
LGTM. Tested on Android/NW

**Pull request merged**
