### PR TITLE
translate global preferences (#4088)

### PR DESCRIPTION
**Pull request by thomashaury**

### CODE REVIEW

**Comment by matiu** [comment]
ACK! Thanks for the contribution.

**Comment by JDonadio** [comment]
We already made this change here: https://github.com/bitpay/copay/pull/4088

Thanks @thomashaury !

**Comment by matiu** [comment]
ugh.. Closing this one then.

What happen with that change @cmgustavo ? It is not on master?

**Comment by cmgustavo** [comment]
No, it was merged in a wrong place.

**Pull request merged**
