### PR TITLE
Use icon properly - confirm view

### PR DESCRIPTION
**Pull request by JDonadio**
Fixes https://github.com/bitpay/copay/issues/4846

### CODE REVIEW

**Comment by JDonadio** [comment]
Updated

**Comment by gabrielbazan7** [comment]
Different text size here 
cursor_and_copay_-_copay_bitcoin_wallet

**Comment by JDonadio** [comment]
Ready for review. Thanks guys!

**Comment by JDonadio** [comment]
Updated. Thank you guys!

**Comment by gabrielbazan7** [comment]
ACK

**Pull request merged**
