### PR TITLE
Update splash images. Support iPhone X full screen

### PR DESCRIPTION
**Pull request by cmgustavo**
* Updates mechanism to display a launch screen on iOS: **Launch storyboard images** (Ref. https://github.com/apache/cordova-plugin-splashscreen#launch-storyboard-images)
* Remove old splash images
* Full screen support for iPhone X (5.8'')
* Updates the plugin-ionic-webview

====== Warning =======

There is an issue with the splash plugin that shows the image twice at starting app.

It has been reported on Apache issue tracker: https://issues.apache.org/jira/browse/CB-13505?filter=-4&jql=project%20%3D%20CB%20ORDER%20BY%20createdDate%20DESC

They also sent a solution to `cordova-ios` repository: https://github.com/apache/cordova-ios/pull/345

====================

### CODE REVIEW

**Comment by guerrerocarlos** [comment]
@cmgustavo how are you? one question, how do you build this branch? just following the README.md? Doesn't work from me (either from /bitpay/copay's master) modules versions in node_modules seem to generate many bugs, could you please share your package-lock.json ?

**Comment by cmgustavo** [comment]
Try: 

```
npm run clean-all; npm run apply:copay; npm start; open http://localhost:8100
```
If it doesn't work, please open an issue with the error.

Thanks.

**Comment by guerrerocarlos** [comment]
@cmgustavo can I ask what version of node, npm and grunt do you use?

**Comment by cmgustavo** [comment]
Node v8.7.0
npm v5.5.1
grunt-cli v1-2-0

**Comment by guerrerocarlos** [comment]
Roger that, issue created:
https://github.com/bitpay/copay/issues/7019

**Pull request merged**
