### PR TITLE
save lang and unit in BWS (for notifications)

### PR DESCRIPTION
**Pull request by matiu**
Saves `lang` and `unit` setting on BWS for better emails.

This is triggered on changing the language or unit setting, or when setting the email.

On the first 2 cases, all wallet settings will be updated.
When changing the email only the focused wallet will be updated.

### CODE REVIEW

**Comment by matiu** [comment]
updated.

**Comment by cmgustavo** [comment]
Great job! LGTM

**Comment by isocolsky** [comment]
I don't know if this is related to changes in this PR.

I recreated a testnet wallet I already had on my profile.
I pointed Copay to the staging BWS.
Copay asked me to recreate the wallet which I did. Balance of 0 BTC was shown (correct)
I now change either the unit preferences or the language preferences.
When I go back to the home screen, Copay asks me to recreate my wallet.

BTW I have other non-recreated wallets on the same profile.

**Comment by matiu** [comment]
@isocolsky the last commit at https://github.com/bitpay/copay/pull/2940 should fix that problem (it is not related to this PR), nice catch.

**Comment by isocolsky** [comment]
Great thanks. Once #2940 is merged I will retest.

**Pull request merged**
