### PR TITLE
WIP: Lock Copay App - Fingerprint

### PR DESCRIPTION
**Pull request by JDonadio**
* Moved: fingerprint option to global setting
* Prevents to show any wallet and balance if it's enabled
* Remove fingerprint control in backup, export, and send flows
* Add lock/unlock control on sidebar
* Error page

Closes https://github.com/bitpay/copay/issues/4555
Closes https://github.com/bitpay/copay/issues/4617

### CODE REVIEW

**Comment by dabura667** [comment]
utACK

I guess I'll have to set a password now... I liked the way it was with only fingerprinting for sensitive actions.

Since we have no way to show the receive address without unlocking the app, someone could grab my phone from me while I am showing them my QR in the app and send all to their address.

I don't see why there is a need to remove it from all sensitive actions as well.

**Comment by dabura667** [comment]
I like the way breadwallet does it:

1. Allow the user into the app with no pin or touchID.
2. Have a button for unlocking balance and history display. This asks you for auth.
3. ALSO ask for auth before every sensitive action.

**Comment by dabura667** [comment]
This way you can access receive address

**Comment by cmgustavo** [comment]
Needs rebase

**Comment by JDonadio** [comment]
Updated

**Comment by dmo580** [comment]
@dabura667 i don't see the point of only protecting sensitive actions. The app already had a send password option previously. One of the major complaints has been no ability to lock the app (zero user access until one enters PIN/fingerprint).

Also I don't see the app being locked in Android with fingerprint.

**Pull request closed without merging**
