### PR TITLE
Use cordova-plugin to paste from clipboard on mobile

### LINKED ISSUE #3832: App responsiveness review
Tested in IOS

Not OK:
starting from the not running
- [ ] opening / closing the wallet settings takes a while
- [ ] tapping on a tx to see its details take a while (closing it is faster)
- [ ] tapping on add  wallet / settings / buy & sell -> first close the side panel, and then shows the popup, it should be otherwise
- [x] the wallet icon on send to popup the address book has an action area too small
- [ ] Delay after pressing `Set/Ok` button in the popup if request password is required
- [ ] changing the focused wallet should not refresh the balance (the balance should be refreshed on background for wallet wallets).

OK:
 - qr reader popups and closes really fast!
 - switching between send/activity/recv
 - opening the side menu

### PR DESCRIPTION
**Pull request by cmgustavo**
Also fixes #3832 , #3859

### CODE REVIEW

**Comment by matiu** [comment]
reviewing

**Comment by matiu** [comment]
What about copying the addr from the clipboard when focusing the send

**Comment by cmgustavo** [comment]
Great idea!

**Comment by cmgustavo** [comment]
Updated

**Pull request merged**
