### PR TITLE
Wallet tabs

### PR DESCRIPTION
**Pull request by msalcala11**
Replaces the global send/receive wallet tabs with in-wallet send/receive tabs to improve the intuitiveness of sending and receiving funds. Also adds a new reusable action sheet component that can be used to show tips, and present options.

### CODE REVIEW

**Comment by cmgustavo** [comment]
I found another issue when I change BWS URL (it simulates if BWS is down):

I got error if click on Receive or Send buttons. 

```

![screen shot 2018-07-12 at 16 44 48](https://user-images.githubusercontent.com/237435/42655603-078c603a-85f3-11e8-8c6d-274fcacdd165.png)

**Comment by cmgustavo** [comment]
LGTM! Issues have been solved.

**Comment by bitjson** [comment]
ACK! 🚀

**Comment by cronos-polis** [comment]
@msalcala11 
I don't know if is my testing environment but I have seen an issue. 
When you try to send coins from the send tab if you use the send max button using USD the form displays incorrect information.
I tested it using bch.

**Comment by msalcala11** [comment]
@cronos-polis thanks for sharing! I'm now seeing the issue as well. Working on a fix 👍

**Pull request merged**
