### PR TITLE
Ref: History update and walletHome/Index reset when chaning wallet

### PR DESCRIPTION
**Pull request by matiu**
- Completely delete index and walletHome scopes when a new wallet is focused
 - Show tx history while syncing

### CODE REVIEW

**Comment by JDonadio** [comment]
LGTM. Great job!

**Comment by matiu** [comment]
updated for mobile.

**Comment by matiu** [comment]
updated & rebased and working on mobile (tested on ios + ios sim)

**Comment by JDonadio** [comment]
I found a little bug, in send tab is not showing the unit and if you tab on it does not change.

**Comment by matiu** [comment]
updated. Thanks @JDonadio for your comment.

**Comment by cmgustavo** [comment]
ACK. Tested on iOS and OSX (desktop). Good job! This works lighter!

**Pull request merged**
