### PR TITLE
Portuguese Brazilian translation

### PR DESCRIPTION
**Pull request by pmichelazzo**
The Portuguese Brazilian translation

### CODE REVIEW

**Comment by pmichelazzo** [comment]
Guys,
I just made the translations of .po and appstore files because I can't find other files to translate into my native language.

I the app have something more, let me know.

Best regards and congrats for the job. It's amazing!

**Comment by matiu** [comment]
This is awesome!!! Thanks a lot!!

**Comment by pmichelazzo** [comment]
My pleasure.

If possible, tagged the files for translation. It’s easy for everyone help with it.

Regards!

**Comment by matiu** [comment]
Sure, will do!

**Pull request merged**
