### PR TITLE
WIP: Fix rounding error in amount field

### PR DESCRIPTION
**Pull request by cmgustavo**
Javascript rounding error. The following operations should be equals:

```
101808500 * 1 / 100000000 = 1.018085
```
But not...
```
101808500 * 0.00000001 = 1.0180850000000001
```

### CODE REVIEW

**Comment by matiu** [comment]
Please:

1) add test to prevent this to get broken one more time
2) remove `satToUnit` if it is not longer used.

**Comment by cmgustavo** [comment]
Updated!

1.- Tests added. 
2.- Unused variable removed.

Note:
All floating point math is based on the IEEE 754 standard. JavaScript uses 64-bit floating point representation, which is the same as Java's double.

**Comment by matiu** [comment]
Awesome, great work

**Comment by MeniRosenfeld** [comment]
It seems the problem still/again exists.

image

**Pull request merged**
