### PR TITLE
Refresh external service on settings-tab

### PR DESCRIPTION
**Pull request by cmgustavo**

### CODE REVIEW

**Comment by JDonadio** [comment]
Can you try removing the 100 ms in the timeouts? Because if the process takes less than 100 ms the redrawing view experience will be faster.

**Comment by cmgustavo** [comment]
Yes, it works without adding 100ms. Thanks.

**Comment by JDonadio** [comment]
Actually if you are using `apply` or `digest` within an async function you don't need the timeouts (untested)

**Comment by cmgustavo** [comment]
Code obsolete. Closes #5544

**Pull request closed without merging**
